version: "3.7"
services:
  app:
    container_name: "app"
    restart: always
    build: .
    ports:
      - 80:80
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    container_name: "hydra_database"
    image: mongo
    ports:
      - 27017:27017