version: '3'
services:
  node:
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: "hydra_webserver"
    restart: 'always'
    links:
      - mongodb
    ports:
      - 80:3000
    volumes:
      - ./:/app

  mongodb:
    container_name: "hydra_database"
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js